type User {
  id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  email: String
  active: Boolean!
}

type Query {
  user(id: ID!): User!
  users: [User!]!
}

input UserInput {
  firstName: String!
  lastName: String!
  email: String
  active: Boolean!
}

type Mutation {
  createUser(data: UserInput!): User!
  updateUser(id: ID!, data: UserInput!): User!
  deleteUser(id: ID!): Boolean 
}